# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk
          
    working_directory: ~/flapweb-auth-service
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      - run: mvn package

      - store_test_results:  
          path: target/surefire-reports

      - store_artifacts:
          path: target/flapweb-auth-service-1.war

  deploy:
   machine: 
     enabled: true
   steps: 
     - run:
         name: Deploy Over SSH
         command: 
     - "scp target/flapweb-auth-service-1.war $CIUSER@$HOST:$PATH"



workflows:
  version: 2
  build-and-deploy:
    jobs:
        - build
        - deploy:
          requires:
            - build
          filters:
            branches: 
              only: master
